import React from 'react';
import { createRoot } from 'react-dom/client';
import { motion } from 'framer-motion';
import { ArrowDownRight, Menu, X } from 'lucide-react';
import './styles.css';

const projects=[
 {name:'Casa Amato',place:'Jardins, São Paulo',status:'Disponível',image:'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1800&q=85'},
 {name:'Lima Residence',place:'Vila Nova Conceição',status:'Em andamento',image:'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1800&q=85'},
 {name:'Casa Pinheiros',place:'Alto de Pinheiros',status:'Vendido',image:'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1800&q=85'}
];
function App(){const [open,setOpen]=React.useState(false);return <main><header><a className="brand">AMATO LIMA</a><button onClick={()=>setOpen(!open)} aria-label="menu">{open?<X/>:<Menu/>}</button><nav className={open?'open':''}><a href="#sobre">Sobre nós</a><a href="#viver">Viver quiet luxury</a><a href="#projetos">Projetos</a><a href="#contato">Contato</a><a href="#portal">Portal do cliente</a></nav></header><section className="hero"><div className="hero-image"/><div className="hero-copy"><span>IMÓVEIS • ARQUITETURA • PATRIMÔNIO</span><h1>O luxo de<br/><i>viver bem.</i></h1><p>Residências excepcionais em endereços que atravessam gerações.</p><a className="link" href="#projetos">Explorar projetos <ArrowDownRight size={18}/></a></div></section><section id="sobre" className="intro"><span>01 — AMATO LIMA</span><div><h2>Onde a arquitetura encontra o tempo.</h2><p>Compramos, transformamos e entregamos imóveis singulares nos bairros mais desejados de São Paulo. Uma curadoria pautada por permanência, matéria e beleza silenciosa.</p></div></section><section id="viver" className="statement"><p>Quiet luxury is not about having more.</p><h2>É sobre escolher <i>melhor.</i></h2></section><section id="projetos" className="projects"><div className="section-head"><span>02 — PROJETOS</span><h2>Espaços para<br/><i>chamar de lar.</i></h2></div><div className="grid">{projects.map((p,i)=><motion.article key={p.name} initial={{opacity:0,y:30}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{delay:i*.12}}><div className="project-image" style={{backgroundImage:`url(${p.image})`}}/><div className="project-meta"><div><span>{p.status}</span><h3>{p.name}</h3><p>{p.place}</p></div><ArrowDownRight/></div></motion.article>)}</div></section><section id="contato" className="contact"><span>03 — CONTATO</span><h2>Vamos encontrar<br/><i>seu próximo lugar.</i></h2><a className="link" href="mailto:contato@amatolima.com.br">Fale conosco <ArrowDownRight size={18}/></a></section><footer><strong>AMATO LIMA</strong><span>São Paulo · Brasil</span><span>© 2026 Amato Lima</span></footer></main>}
createRoot(document.getElementById('root')).render(<App/>);